builders:
  module_generator:
    import: "package:knife_generator/module_part_builder.dart"
    builder_factories: ["modulePartBuilder"]
    build_extensions: { ".dart": [".module.dart"] }
    auto_apply: dependents
    build_to: source
  dependency_injector:
    import: "package:knife_generator/component_library_builder.dart"
    builder_factories: ["componentLibraryBuilder"]
    build_extensions: { ".dart": [".component.dart"] }
    auto_apply: dependents
    build_to: source
